version: '2'

services:
  tomcat:
    image: 'docker.io/bitnami/tomcat:9.0-debian-10'
    ports:
      - '8080:8080'
    volumes:
      - 'tomcat_data:/bitnami'

volumes:
  tomcat_data:
    driver: local
